# Generated by Django 5.0 on 2025-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name of the user",
                max_length=30,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Last name of the user",
                max_length=30,
                null=True,
                verbose_name="Last Name",
            ),
        ),
    ]
