fail_fast: false
exclude: ^.*\b(migrations)\b.*$|^.*__init__\.py$|asgi.py|
repos:

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--line-length=120"]
        stages: [pre-commit]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
        stages: [pre-commit]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [pre-commit]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        stages: [pre-commit]
        exclude: ^/annotes\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--extend-ignore=A003,A005,E722"
        exclude: .git|__pycache__
        additional_dependencies:
          - flake8-builtins>=1.5.3
          - flake8-commas>=2.0.0
          - flake8-debugger>=4.0.0
          - flake8-comprehensions>=3.3.1
          - flake8-eradicate>=1.0.0
          - dlint>=0.11.0
        stages: [pre-commit]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - "--in-place"
          - "--blank"
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: services/auth/src/core/middlewares.py
        stages: [pre-commit]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
          - "--remove-unused-variables"
        stages: [pre-commit]
