# Generated by Django 5.0 on 2025-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='raiting',
            field=models.IntegerField(blank=True, help_text='Raiting of the establishment', null=True, verbose_name='Raiting'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_wifi',
            field=models.BooleanField(default=False, help_text='Does the establishment have WiFi?', verbose_name='Has WiFi'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='open_at_on_monday_to_friday',
            field=models.IntegerField(blank=True, help_text='Open at on Monday to Friday', null=True, verbose_name='Open At on Monday to Friday'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='open_at_on_saturday',
            field=models.IntegerField(blank=True, help_text='Open at on Saturday', null=True, verbose_name='Open At on Saturday'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='raiting',
            field=models.FloatField(blank=True, default=0.0, help_text='Raiting of the establishment', null=True, verbose_name='Raiting'),
        ),
    ]
