# Generated by Django 5.0 on 2025-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0002_comment_raiting_establishment_has_wifi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Address of the establishment",
                max_length=255,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact email of the establishment",
                max_length=255,
                null=True,
                verbose_name="Contact Email",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the establishment",
                max_length=255,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="has_bathroom",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the establishment have a bathroom?",
                null=True,
                verbose_name="Has Bathroom",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="has_elevator",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the establishment have an elevator?",
                null=True,
                verbose_name="Has Elevator",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="has_parking",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the establishment have parking?",
                null=True,
                verbose_name="Has Parking",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="has_ramp",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the establishment have a ramp?",
                null=True,
                verbose_name="Has Ramp",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="has_signage",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the establishment have signage?",
                null=True,
                verbose_name="Has Signage",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="has_tactical_floor",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the establishment have a tactical floor?",
                null=True,
                verbose_name="Has Tactical Floor",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the student",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="phone",
            field=models.IntegerField(
                blank=True,
                help_text="Phone of the establishment",
                null=True,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Website of the establishment",
                max_length=255,
                null=True,
                verbose_name="Website",
            ),
        ),
    ]
