# Generated by Django 5.0 on 2025-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0003_alter_establishment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the establishment', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the establishment', null=True, verbose_name='Longitude'),
        ),
    ]
