services:
  front-prod:
    build:
      context: ../..
      dockerfile: docker_compose/front/Dockerfile-prod
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules 
    networks:
      - backend-prod
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_HOST=${API_HOST}
    command: npm start
    stdin_open: true
    tty: true


  nginx-prod:
    build:
      context: ../..
      dockerfile: docker_compose/nginx/Dockerfile-prod
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - front-prod
    links:
      - front-prod
    networks:
      - backend-prod
networks:
  backend-prod:
    external: true